# Generated by Django 3.2.4 on 2023-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(null=True, related_name='recipes', through='api.IngredientInRecipe', to='api.Ingredient', verbose_name='Ингредиенты рецепта'),
        ),
    ]
