# Generated by Django 3.2.4 on 2023-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='api.IngredientInRecipe', to='api.Ingredient', verbose_name='Ингредиенты рецепта'),
        ),
    ]
